RAW_DATASET_PATH = "data/raw_data/"
PROCESSED_METADATA_FILES_PATH = "data/info_repos/infos/"
PROCESSED_RELEASE_FILES_PATH = "data/info_repos/release_number/"
PROCESSED_README_FILES_PATH = "data/info_repos/readme/"
PROCESSED_METADATA_PATH = "data/metadata/"
PROCESSED_DF_PATH = "data/info_repos/assembled_df/"
